import os

# DISCOVERY PARAMETERS
DISCOVERY_MIN_PRICE = 1.0
DISCOVERY_MAX_PRICE = 20.0
DISCOVERY_MIN_GAP = 8.0
DISCOVERY_MAX_GAP = 100.0

# VALIDATION PARAMETERS
VALIDATION_MAX_SPREAD = 1.5
VALIDATION_MIN_PM_VOLUME_ABS = 100_000
VALIDATION_MIN_PM_BARS = 10
VALIDATION_MAX_PM_DIST = 5.0
VALIDATION_MIN_VWAP_DIST = 0.0

# RVOL & CATALYST
VALIDATION_MIN_RVOL = 0.0          # Informational / disabled until historical baseline is available
VALIDATION_MIN_CATALYST_SCORE = 3.0
