import os

ALPACA_API_KEY    = os.getenv("ALPACA_API_KEY")
ALPACA_SECRET_KEY = os.getenv("ALPACA_SECRET_KEY")

FINNHUB_API_KEY   = os.getenv("FINNHUB_API_KEY")
FMP_API_KEY       = os.getenv("FMP_API_KEY")

TELEGRAM_TOKEN    = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID  = os.getenv("TELEGRAM_CHAT_ID")

MIN_PRICE         = 1.0
MAX_PRICE         = 20.0
MAX_MARKET_CAP    = 2_000_000_000

MIN_GAP_PCT       = 5.0
MIN_PREMARKET_VOL = 50_000

MIN_SCORE         = 60
